import type { Project } from "./types";

export const projects: Project[] = [
  {
    id: "sellora",
    title: "Sellora",
    year: "2026",
    type: "Web + Mobile",
    featured: true,
    category: "Sales & inventory",
    summary: "Sales and inventory app for small businesses: an online Next.js web dashboard and a Flutter mobile app that works offline or online.",
    platforms: "Web · Android · iOS",
    users: "10+",
    live: "https://sellora-world.vercel.app/",
    image: { src: "/images/sellora-mobile.png", alt: "Sellora mobile app on three phones showing the dashboard, menu, and sales reports", width: 3200, height: 2000, position: "center" },
    stack: ["Next.js", "Flutter", "Supabase", "SQLite", "React", "Recharts", "Dart", "Riverpod", "ML Kit"],
    indexStack: ["Next.js", "Supabase", "Flutter"],
    detail: {
      overview: [
        "Sellora is a sales and inventory platform for small businesses, from retail stores to water stations and rentals. Owners record sales, track stock, log expenses, and read their numbers in one place.",
        "The web app runs online on Next.js and Supabase. The Flutter mobile app is offline-first: everything is saved in a SQLite database on the phone, so it keeps working through a brownout, a dead signal, or a week without data, and it can go online when a connection is available.",
      ],
      features: [
        "Mobile app on Android and iOS that works offline or online",
        "Run several businesses from one account and switch in a tap",
        "Log a sale or expense by typing a single line",
        "Notebook Capture: photograph a page of a paper sales notebook to bring it into the app",
        "Plain-language insights, like which day of the week is slowest",
        "Revenue, expense, profit, and top-product reports, with PDF export on the web",
      ],
    },
  },
  {
    id: "safeship",
    title: "Safeship",
    year: "2026",
    type: "Web + AI",
    featured: true,
    category: "Developer security",
    summary: "A security co-pilot for people who build with AI tools. Connect a GitHub repo and it finds leaked secrets, insecure code, and vulnerable dependencies, then explains each fix in plain English.",
    platforms: "Web",
    users: "20+",
    live: "https://safeship-h9zu.vercel.app/",
    repo: "https://github.com/jigabarda/Safeship",
    image: { src: "/images/AdvisorPage.png", alt: "Safeship Advisor page for reviewing a repository's schema, tech stack, and structure", width: 1917, height: 907 },
    stack: ["Next.js", "Semgrep", "Groq", "GitHub Actions", "gitleaks", "OSV-Scanner", "Prisma", "PostgreSQL", "Auth.js", "Ollama"],
    detail: {
      overview: [
        "Safeship is a security co-pilot for people who build with AI tools. Connect a GitHub repository and it scans the code for leaked secrets, insecure patterns, and vulnerable dependencies, then explains every finding in plain English, ranked by real-world risk, with a copy-paste fix.",
        "Scans run on on-demand GitHub Actions runners with gitleaks, Semgrep, and OSV-Scanner. Secrets are redacted before anything leaves the runner, and the cloned code is destroyed when the job ends. It is static analysis only: Safeship never probes or sends traffic to live systems.",
      ],
      features: [
        "Secret, code (SAST), and dependency scanning in a single run",
        "Plain-English explanations and a 0–100 safety score for every scan",
        "Fix with AI: opens a pull request that resolves a finding",
        "Advisor reviews a repo's schema, tech stack, and structure, and draws its tables",
        "Assistant chat for security and code questions",
        "Runs on Groq in the cloud or fully local with Ollama",
      ],
    },
  },
  {
    id: "broadcast",
    title: "Broadcast Management System",
    year: "2025",
    type: "Web + Mobile",
    featured: false,
    repo: "https://github.com/jigabarda/BMS-Web",
    image: { src: "/images/broadcast.png", alt: "Broadcast Management System dashboard", width: 1269, height: 572 },
    stack: ["Rails", "Next.js", "PostgreSQL"],
  },
  {
    id: "mentra",
    title: "Mentra",
    year: "2025",
    type: "Web + AI",
    featured: false,
    repo: "https://github.com/jigabarda/Mentra",
    image: { src: "/images/mentra.png", alt: "Mentra AI career coach", width: 1365, height: 628 },
    stack: ["Next.js", "Supabase", "OpenAI"],
  },
  {
    id: "lms",
    title: "Learning Management System",
    year: "2025",
    type: "Web",
    featured: false,
    repo: "https://github.com/jigabarda/LeaningManagementSystem",
    image: { src: "/images/cms.png", alt: "Learning Management System", width: 1365, height: 630 },
    stack: ["Next.js", "Supabase", "Tailwind"],
  },
  {
    id: "bms",
    title: "Barangay Management System",
    year: "2025",
    type: "Desktop, client work",
    featured: true,
    category: "Local government",
    summary: "A desktop app that runs a barangay office's records in one place: residents, households, certificates, blotter reports, and finances, with certificates issued as ready-to-print PDFs.",
    platforms: "Desktop",
    users: "5+",
    private: true,
    image: { src: "/images/bms2.jpg", alt: "Barangay Management System dashboard with youth demographics charts", width: 2048, height: 1223, position: "center" },
    stack: ["Tauri", "React", "TypeScript", "Rust", "SQLite", "TanStack Query", "React PDF", "Tailwind CSS", "Zod"],
    indexStack: ["Tauri", "React", "Rust"],
    detail: {
      overview: [
        "A desktop app built with Appnado IT Solutions to help local government units run their barangay offices: resident and household records, certificates, blotter reports, events, and finances in one place.",
        "Built on Tauri, with a React and TypeScript interface and a Rust backend that stores everything in a local SQLite database, so records stay on the office computer and the app works without an internet connection.",
      ],
      features: [
        "Resident and household records with search and bulk actions",
        "Certificates issued from templates as ready-to-print PDFs",
        "Blotter records for filing and reviewing incident reports",
        "Youth registry for the Sangguniang Kabataan, including SK voter and school or work status",
        "Barangay officials, events, income, and expense tracking",
        "Dashboard with charts of the barangay's key numbers",
      ],
    },
  },
  {
    id: "resort",
    title: "Resort Reservation App",
    year: "2025",
    type: "Mobile",
    featured: false,
    repo: "https://github.com/jigabarda/ResortReservationApp",
    thumbInitials: "RR",
    stack: ["React Native", "Expo", "Google Maps"],
  },
  {
    id: "prolock",
    title: "ProLock",
    year: "2024",
    type: "IoT + Desktop",
    featured: false,
    private: true,
    image: { src: "/images/prolock.png", alt: "ProLock attendance system", width: 1728, height: 970 },
    stack: ["Python", "C#", "Raspberry Pi", "RFID"],
    indexStack: ["Python", "C#", "Raspberry Pi", "RFID"],
  },
  {
    id: "ecommerce",
    title: "E-commerce Platform",
    year: "2024",
    type: "Web + Mobile",
    featured: false,
    private: true,
    image: { src: "/images/ecom.png", alt: "E-commerce platform", width: 1280, height: 568 },
    stack: ["React Native", "Expo", "Firebase"],
  },
];

export const featuredProjects = projects.filter((p) => p.featured);

/** Projects with a full write-up get their own page; the rest only appear in the index. */
export const projectPages = projects.filter((p) => p.detail);

export function projectPath(id: string): string {
  return `/projects/${id}`;
}
